name: "EventToolBox"

on:
  push:
    branches: [ Ops-TestCICD ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker-compose -f compose.yml build

      - name: Run Docker Compose
        run: |
          docker-compose -f compose.yml up -d
          docker-compose -f compose.yml ps

      - name: Wait for services to start
        run: sleep 30

      - name: Verify Docker Containers
        run: |
          docker ps -a
          docker logs <container_name>  # Replace <container_name> with the actual container name to check logs

      - name: Tear down
        if: always()
        run: docker-compose -f compose.yml down
