name: "EventToolBox"

on:
  push:
    branches: [ Ops-TestCICD ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}} 
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: publish to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          # tags: latest, ${{github.run_number }}
          tags: chayma02/eventmanager:latest
          # tags: latest, ${{github.run_number }}


        ##### create an artifact for local download 
        ########## this is not the main goal
      

      # - name: build docker image for frontend
      #   run: cd ./frontend && ls && npm install && npm run build

        

      # - name: upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: MernStack
      #     path: ./frontend

















          ########## this part is meant for docker compose which is not taken in consideration for the moment

      # - name: Build Docker images
      #   run: |
      #     docker-compose -f compose.yml build

      # - name: Run Docker Compose
      #   run: |
      #     docker-compose -f compose.yml up -d
      #     docker-compose -f compose.yml ps

      # - name: npm run dev
      #   run: nmp run dev





      # - name: upload artifacts
      #   # working-directory: /app/backend
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: MernStack
      #     path: .git/
      # - name: Wait for services to start
      #   run: sleep 30



      

      # - name: Verify Docker Containers
      #   run: |
      #     docker ps -a

    #  - name: Tear down
    #    if: always()
    #    run: docker-compose -f compose.yml down
