name: "EventToolBox"

on:
  push:
    branches: [ Ops-TestCICD ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose -f compose.yml build

      - name: Run Docker Compose
        run: |
          docker-compose -f compose.yml up -d
          docker-compose -f compose.yml ps

      - name: npm run dev
        run: nmp run dev

      - name: upload artifacts
        uses: action/upload-artifact@v3
        with:
          name: MernStack
          path: ./backend

      - name: Wait for services to start
        run: sleep 30

      - name: Verify Docker Containers
        run: |
          docker ps -a

#      - name: Tear down
#        if: always()
#        run: docker-compose -f compose.yml down
